name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.17
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
      - name: Run script
        run: mix run test_script.exs
      - name: Run mix task
        run: mix gh_tls_test.get
      - name: Run mix npm_deps.get
        run: mix npm_deps.get
